routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', 'CarController@index')->name('home.page');

Route::name('car.')->group(function () {
    Route::get('car/detail/{id}', 'CarController@detail')->name('detail');
});


Route::name('admin.')->prefix('admin')->namespace('Admin')->group( function (){

    Auth::routes(['verify' => true]);

    Route::get('/home', 'HomeController@index')->name('home');

    Route::resource('cars', 'CarController');
    Route::post('/car/position/update', 'CarController@update_position');
    Route::get('car/restore/{id}', 'CarController@restore')->name('car.restore');
    Route::get('cars/restore_all', 'CarController@restore_all')->name('cars.restore_all');
    Route::delete('car/delete_image', 'CarController@delete_image')->name('car.delete.image');
});


Route::group(['prefix' => 'admin'], function () {
    Route::resource('sellers', 'Admin\SellerController', ["as" => 'admin']);
});

app/Models/Car.php
<?php

namespace App\Models;

use App\Models\CarImage;
use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class Car
 * @package App\Models
 * @version April 26, 2020, 10:24 am UTC
 *
 * @property integer $id
 * @property string $reference
 * @property string $brand
 * @property string $make
 * @property string $model
 * @property string $fuel_type
 * @property string $engine
 * @property string $mileage
 * @property string $transmission
 * @property integer $gears_num
 * @property string $body_style
 * @property string $type
 * @property string $state
 * @property integer $year
 * @property integer $price
 * @property string $localisation
 * @property string $status
 * @property string $description
 * @property integer $seller_id
 * @property boolean $visibility
 * @method static all()
 * @method static whereVisibility(int $int)
 */
class Car extends Model
{
    use SoftDeletes;

    public $table = 'cars';

    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';

    public $fillable = [
        'reference',
        'position',
        'brand',
        'make',
        'model',
        'fuel_type',
        'engine',
        'mileage',
        'transmission',
        'gears_num',
        'body_style',
        'type',
        'state',
        'year',
        'price',
        'localisation',
        'status',
        'description',
        'seller_id',
        'visibility'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'reference' => 'string',
        'position' => 'integer',
        'brand' => 'string',
        'make' => 'string',
        'model' => 'string',
        'fuel_type' => 'string',
        'engine' => 'string',
        'mileage' => 'string',
        'transmission' => 'string',
        'gears_num' => 'integer',
        'body_style' => 'string',
        'type' => 'string',
        'state' => 'string',
        'year' => 'integer',
        'price' => 'integer',
        'localisation' => 'string',
        'status' => 'string',
        'description' => 'string',
        'seller_id' => 'integer',
        'visibility' => 'boolean'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'brand' => 'required',
        'make' => 'required',
        'model' => 'required',
        'fuel_type' => 'required',
        'engine' => 'required',
        'mileage' => 'required',
        'type' => 'required',
        'state' => 'required',
        'year' => 'required',
        'price' => 'required',
        'localisation' => 'required',
        'status' => 'required',
        'description' => 'required'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     **/
    public function carImages()
    {
        return $this->hasMany(CarImage::class, 'car_id');
    }

    public function seller()
    {
        return $this->belongsTo(Seller::class, 'seller_id');
    }
}

app/Models/CarImage.php
<?php

namespace App\Models;

use App\Models\Car;
use Illuminate\Database\Eloquent\Model;

/**
 * @method static create(array $array)
 */
class CarImage extends Model
{
    public $table = 'car_images';

    public $fillable = [
        'name', 'car_id'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'name' => 'string',
        'car_id' => 'integer'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function car()
    {
        return $this->belongsTo(Car::class, 'car_id')->withTrashed();
    }

    /**
     * Get the path of the image
     * @return string
     */
    public function getImageUrlAttribute()
    {
        return asset('storage/cars/' . $this->car->id . '/' . $this->name);
    }
}

app/Http/Controllers/Admin/CarController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\Admin\CreateCarRequest;
use App\Http\Requests\Admin\UpdateCarRequest;
use App\Models\Admin;
use App\Models\Car;
use App\Models\CarImage;
use App\Models\Seller;
use App\Repositories\Admin\CarRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Intervention\Image\Facades\Image;
use Laracasts\Flash\Flash;
use Response;
use function foo\func;

class CarController extends AppBaseController
{
    /** @var  CarRepository */
    private $carRepository;

    public function __construct(CarRepository $carRepo)
    {
        $this->carRepository = $carRepo;
        $this->middleware('auth:' . Admin::GUARD);
    }

    /**
     * Display a listing of the Car.
     *
     * @return \Illuminate\View\View
     */
    public function index()
    {
        $cars = $this->carRepository->all()->sortBy('position');
        $trashed_cars = Car::onlyTrashed()->get();

        return view('admin.cars.index')->with(['cars' => $cars, 'trashed_cars' => $trashed_cars]);
    }

    /**
     * Update position of a car
     * @param Request $request
     */
    public function update_position(Request $request)
    {
        $cars = Car::all();
        foreach ($cars as $car){
            $car->timestamps = false;
            $id = $car->id;

            foreach ($request->positions as $position){
                if ($position['id'] == $id)
                    $car->update(['position' => $position['position']]);
            }
        }
    }
    /**
     * Show the form for creating a new Car.
     *
     * @return \Illuminate\View\View
     */
    public function create()
    {
        $current_year = (int) date('Y');
        $years = collect(range($current_year - 30, $current_year))->mapWithKeys(function ($item){
            return [$item => $item];
        });

        $sellers = Seller::all()->mapWithKeys(function ($item){
           return [$item->id => $item->full_name . ' (' . $item->phone_number . ')'];
        });

        return view('admin.cars.create', compact('years', 'sellers'));
    }

    /**
     * Store a newly created Car in storage.
     *
     * @param CreateCarRequest $request
     *
     * @return \Illuminate\Routing\Redirector
     */
    public function store(CreateCarRequest $request)
    {
        $input = $request->all();
        $input += ['position' => Car::all()->count() + 1];

        $car = $this->carRepository->create($input);
        $car->update(['reference' => $this->generate_ref($car->id)]);

        $this->insert_images($request, $car);

        Flash::success('Car saved successfully.');

        return redirect(route('admin.cars.index'));
    }

    /**
     * Display the specified Car.
     *
     * @param int $id
     *
     * @return \Illuminate\Routing\Redirector|\Illuminate\View\View
     */
    public function show($id)
    {
        $car = $this->carRepository->find($id);

        if (empty($car)) {
            Flash::error('Car not found');

            return redirect(route('admin.cars.index'));
        }

        return view('admin.cars.show')->with('car', $car);
    }

    /**
     * Show the form for editing the specified Car.
     *
     * @param int $id
     *
     * @return \Illuminate\Routing\Redirector|\Illuminate\View\View
     */
    public function edit($id)
    {
        $car = $this->carRepository->find($id);

        if (empty($car)) {
            Flash::error('Car not found');

            return redirect(route('admin.cars.index'));
        }
        $current_year = (int) date('Y');
        $years = collect(range($current_year - 30, $current_year))->mapWithKeys(function ($item){
            return [$item => $item];
        });

        $sellers = Seller::all()->mapWithKeys(function ($item){
            return [$item->id => $item->full_name . ' (' . $item->phone_number . ')'];
        });

        return view('admin.cars.edit')->with(['car' => $car, 'edit' => true, 'years' => $years, 'sellers' => $sellers]);
    }

    /**
     * Update the specified Car in storage.
     *
     * @param int $id
     * @param UpdateCarRequest $request
     *
     * @return \Illuminate\Routing\Redirector
     */
    public function update($id, UpdateCarRequest $request)
    {
        $car = $this->carRepository->find($id);

        if (empty($car)) {
            Flash::error('Car not found');

            return redirect(route('admin.cars.index'));
        }

        $car = $this->carRepository->update($request->all(), $id);
        $this->insert_images($request, $car);

        Flash::success('Car updated successfully.');

        return redirect(route('admin.cars.index'));
    }

    /**
     * Remove the specified Car from storage.
     *
     * @param int $id
     *
     * @return \Illuminate\Routing\Redirector
     * @throws \Exception
     *
     */
    public function destroy($id)
    {
        $car = $this->carRepository->find($id);

        if (empty($car)) {
            Flash::error('Car not found');

            return redirect(route('admin.cars.index'));
        }

        $this->carRepository->delete($id);

        Flash::success('Car deleted successfully.');

        return redirect(route('admin.cars.index'));
    }

    /**
     * @param Request $request
     * @param Car|Model $car
     */
    public function insert_images(Request $request, Car $car)
    {
        if ($request->hasFile('images')){
            foreach ($request->file('images') as $image) {
                if (Str::startsWith($image->getClientMimeType(), 'image/')) {
                    $image_name = (string)Str::uuid() . '.' . $image->getClientOriginalExtension();
                    $image_resized = Image::make($image)->resize(750, 500)->encode($image->getClientOriginalExtension());
                    Storage::put('public/cars/' . $car->id . '/' . $image_name, $image_resized);

                    CarImage::create([
                        'name' => $image_name,
                        'car_id' => $car->id,
                    ]);
                }
            }
        }
    }

    public function restore($id)
    {
        Car::onlyTrashed()->where('id', $id)->restore();

        Flash::success('Car restored successfully.');
        return redirect(route('admin.cars.index'));
    }

    public function restore_all()
    {
        Car::onlyTrashed()->restore();

        Flash::success('All Cars restored successfully.');
        return redirect(route('admin.cars.index'));
    }

    public function delete_image(Request $request)
    {
        if ($request->id) {
            $image = CarImage::findOrFail($request->id);
            $image_name = $image->name;
            $car_id = $image->car->id;
            if ($image->delete()) {
                Storage::delete('public/cars/' . $car_id . '/' . $image_name);
            }
        }
    }

    function generate_ref($id)
    {
        $register = (string)$id;
        for ($i = strlen($register); $i < 5; $i++) {
            $register = "0" . $register;
        }
        return "CAR" . $register;
    }

}

app/Http/Controllers/CarController.php
<?php

namespace App\Http\Controllers;

use App\Models\Car;
use Illuminate\Http\Request;

class CarController extends Controller
{
    public function index()
    {
        $cars_to_select = Car::whereVisibility(1)->get();

        $brands = $cars_to_select->map(function ($item){ return $item->brand; })->unique();

        $makes = $cars_to_select->map(function ($item){ return $item->make; })->unique();

        $locations = $cars_to_select->map(function ($item){ return $item->localisation; })->unique();

        $years = $cars_to_select->map(function ($item){ return $item->year; })->unique();

        $types = $cars_to_select->map(function ($item){ return $item->type; })->unique();

        $last_pub = Car::latest()->take(5)->get();

        if (request()->has('select-brand')){

            $brand = request()->get('select-brand');
            $make = request()->get('select-make');
            $location = request()->get('select-location');
            $year = request()->get('select-year');
            $type = request()->get('select-type');

            $cars = Car::with('carImages')
                ->when($brand, function ($query, $brand){
                    return $query->where('brand', 'LIKE', '%'. $brand . '%');
                })
                ->when($make, function ($query, $make){
                    return $query->where('make', 'LIKE', '%'. $make . '%');
                })
                ->when($location, function ($query, $location){
                    return $query->where('localisation', 'LIKE', '%'. $location . '%');
                })
                ->when($year, function ($query, $year){
                    return $query->where('year', 'LIKE', '%'. $year . '%');
                })
                ->when($type, function ($query, $type){
                    return $query->where('type', 'LIKE', '%'. $type . '%');
                })
                ->orderBy('position')->paginate(4);
        }
        else {
            $cars = Car::whereVisibility(1)->with('carImages')->orderBy('position')->paginate(4);
            $last_pub = Car::whereVisibility(1)->latest()->take(5)->with('carImages')->orderBy('position')->paginate(4);
        }

        return view('home_page.index', compact('cars', 'last_pub', 'cars_to_select', 'brands', 'makes', 'locations', 'years', 'types'));
    }

    public function detail($id)
    {
        $car = Car::with('carImages')->find($id);

        return view('car.car-detail', compact('car'));
    }
}

resources/views/admin/cars/car_images.blade.php
<!-- Display product's images -->
<div id="image" class="form-group col-sm-12 carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ul class="carousel-indicators">
        @foreach($car->carImages as $image)
            <li data-target="#image" data-slide-to="{{ $loop->index }}" class="{{ $loop->index == 0 ? 'active' : '' }}"></li>
        @endforeach
    </ul>
    <!-- The slideshow -->
    <div class="carousel-inner border">
        @foreach($car->carImages as $image)
            <div class="{{ $loop->index == 0 ? 'carousel-item  active' : 'carousel-item '}}">
                <div class="dropdown" href="#">
                    <a data-toggle="dropdown">
                        <img src="{{ $image->image_url }}" alt="Product Image" width="1100" height="500" style="width: 100%; height: 100%">
                    </a>
                    @if(count($car->carImages) > 1)
                        <div class="dropdown-menu dropdown-menu-right">
                            <a class="dropdown-item delete-image" id="{{ $image->id }}" style="cursor: pointer; background: #de4350; color: #fff3cd">
                                <i class="fa fa-trash fa-lg"></i> <b>{{__('Delete image')}}</b>
                            </a>
                        </div>
                    @endif
                </div>
            </div>
        @endforeach
    </div>
    <!-- Left and right controls -->
    <a class="carousel-control-prev" href="#image" data-slide="prev">
        <span class="carousel-control-prev-icon"></span>
    </a>
    <a class="carousel-control-next" href="#image" data-slide="next">
        <span class="carousel-control-next-icon"></span>
    </a>
</div>
<!-- End displaying -->

resources/views/admin/cars/create.blade.php
@extends('admin.layouts.app')

@section('content')
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
         <a href="{!! route('admin.cars.index') !!}">{{__('Cars')}}</a>
      </li>
      <li class="breadcrumb-item active">{{__('Create')}}</li>
    </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                <div class="row">
                    <div class="{{--offset-lg-2--}} col-lg-12 {{--offset-lg-2--}}">
                        @include('coreui-templates::common.errors')
                        <div class="card">
                            <div class="card-header">
                                <h3><i class="fa fa-plus-square-o fa-lg"></i> Publier une Voiture</h3>
                            </div>
                            <div class="card-body">
                                {!! Form::open(['route' => 'admin.cars.store', 'enctype' => 'multipart/form-data']) !!}

                                   @include('admin.cars.fields')

                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
           </div>
    </div>
@endsection

resources/views/admin/cars/edit.blade.php
@extends('admin.layouts.app')

@section('content')
    <ol class="breadcrumb">
          <li class="breadcrumb-item">
             <a href="{!! route('admin.cars.index') !!}">{{ __('Cars') }}</a>
          </li>
          <li class="breadcrumb-item active">Editer une Voiture</li>
    </ol>
    <div class="container-fluid">
         <div class="animated fadeIn">
             @include('coreui-templates::common.errors')
             <div class="row">
                 <div class="col-lg-12">
                      <div class="card">
                          <div class="card-header">
                              <h3><i class="fa fa-edit fa-lg"></i> Editer une Voiture</h3>
                          </div>
                          <div class="card-body">
                              {!! Form::model($car, ['route' => ['admin.cars.update', $car->id], 'method' => 'patch', 'enctype' => 'multipart/form-data']) !!}

                              @include('admin.cars.fields')

                              {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
         </div>
    </div>
@endsection

resources/views/admin/cars/index.blade.php
@extends('admin.layouts.app')

@section('styles')
    <!-- Datatables Js-->
    <link rel="stylesheet" type="text/css" href="{{ asset('template/admin/css/datatables.min.css') }}"/>
@endsection

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><h2><b>Liste des Voitures</b></h2></li>
    </ol>
    <div class="container-fluid">
        <div class="animated fadeIn">
             @include('flash::message')
             <div class="row">
                 <div class="col-lg-12">
                     <div class="card">
                         <div class="search">
                             <div class="card-header" style="padding-bottom: 25px;">
                                 <i class="fa fa-align-justify"></i>
                                 {{__('Cars')}}
                                 <a class="pull-right btn btn-primary" href="{{ route('admin.cars.create') }}">
                                     <i class="fa fa-plus fa-lg"></i> <b>Publier une voiture</b>
                                 </a>
                             </div>
                             <div class="card-body">
                                 {{--@include('admin.cars.table')--}}
                                 <div class="table-responsive-sm">
                                     <table id="table" class="table table-bordered table-striped">
                                         <thead>
                                         <tr>
                                             <th>{{__('Image')}}</th>
                                             <th>{{__('Reference')}}</th>
                                             <th>{{__('Brand')}}</th>
                                             <th>{{__('Model')}}</th>
                                             <th>{{__('Fuel Type')}}</th>
                                             <th>{{__('Year')}}</th>
                                             <th>{{__('Price')}}</th>
                                             <th>{{__('Status')}}</th>
                                             <th>{{__('Actions')}}</th>
                                         </tr>
                                         </thead>
                                         <tbody id="table_contents">
                                            @foreach($cars as $car)
                                                <tr class="row1" data-id="{{ $car->id }}">
                                                    <td>
                                                        <img src="{{ $car->carImages->first()->image_url }}" alt="Car Image" style="width: 110px; height: 70px">
                                                    </td>
                                                    <td>{{ $car->reference }}</td>
                                                    <td>{{ $car->brand }}</td>
                                                    <td>{{ $car->model }}</td>
                                                    <td>{{ $car->fuel_type }}</td>
                                                    <td>{{ $car->year }}</td>
                                                    <td>{{ $car->price }}</td>
                                                    <td>{{ $car->status }}</td>
                                                    <td>
                                                        {!! Form::open(['route' => ['admin.cars.destroy', $car->id], 'method' => 'delete']) !!}
                                                        <div class='btn-group'>
                                                            <a href="{{ route('admin.cars.show', [$car->id]) }}" class='btn btn-ghost-success'><i class="fa fa-eye"></i></a>
                                                            <a href="{{ route('admin.cars.edit', [$car->id]) }}" class='btn btn-ghost-info'><i class="fa fa-edit"></i></a>
                                                            {!! Form::button('<i class="fa fa-trash"></i>',
                                                                ['type' => 'submit', 'class' => 'btn btn-ghost-danger'])
                                                            !!}
                                                        </div>
                                                        {!! Form::close() !!}
                                                    </td>
                                                </tr>
                                            @endforeach
                                         </tbody>
                                     </table>
                                 </div>
                                 <div class="pull-right mr-3">

                                 </div>
                             </div>
                         </div>
                     </div>
                  </div>

                 @if($trashed_cars->isNotEmpty())
                     <div class="col-lg-12">
                         <a id="trash" class="btn btn-primary" href="#" style="margin-bottom: 20px">
                             <i class="fa fa-eye"></i> <b>{{__('Trash')}}</b></a>
                     </div>

                     <div class="col-lg-12" id="trashed_cars" style="display: none">
                         <div class="card">
                             <div class="card-header">
                                 <i class="fa fa-align-justify"></i>
                                 Voitures Supprimées
                                 <a class="btn btn-success pull-right" href="{{ route('admin.cars.restore_all') }}">
                                     <i class="fa fa-trash-o"></i> <b>{{__('Restore all')}}</b></a>
                             </div>

                             <div class="card-body">
                                 <div class="table-responsive {{--col-lg-12--}}">
                                     <table class="table table-striped table-bordered">
                                         <thead>
                                         <tr>
                                             <th>{{__('Image')}}</th>
                                             <th>{{__('Brand')}}</th>
                                             <th>{{__('Model')}}</th>
                                             <th>{{__('Fuel Type')}}</th>
                                             <th>{{__('Mileage')}}</th>
                                             <th>{{__('Type')}}</th>
                                             <th>{{__('Year')}}</th>
                                             <th>{{__('Price')}}</th>
                                             <th>{{__('Status')}}</th>
                                             <th>{{ __('Date de Publication') }}</th>
                                             <th>{{__('Actions')}}</th>
                                         </tr>
                                         </thead>
                                         <tbody>
                                         @foreach($trashed_cars as $car)
                                             <tr class="cart_item">
                                                 <td>
                                                     <img src="{{ $car->carImages->first()->image_url }}" style="width: 80px; height: 70px" alt="Car Image">
                                                 </td>
                                                 <td> {{ $car->name }}</td>
                                                 <td> {{ $car->brand }}</td>
                                                 <td> {{ $car->model }}</td>
                                                 <td> {{ $car->fuel_type }}</td>
                                                 <td> {{ $car->mileage }}</td>
                                                 <td> {{ $car->year }}</td>
                                                 <td> {{ $car->price }}</td>
                                                 <td> {{ $car->status }}</td>
                                                 <td> {{ $car->created_at }}</td>
                                                 <td>
                                                     <div>
                                                         <div class='btn-group'>
                                                             <a title="{{__('Restore')}}"
                                                                href="{{ route('admin.car.restore', $car->id) }}"
                                                                class='btn btn-ghost-success'>
                                                                 <i class="fa fa-window-restore"></i>
                                                             </a>
                                                         </div>
                                                     </div>
                                                 </td>
                                             </tr>
                                         @endforeach
                                         </tbody>
                                     </table>
                                 </div>
                             </div>
                         </div>
                     </div>
                 @endif

             </div>
         </div>
    </div>
@endsection

@section('scripts')
    <!-- jQuery UI -->
    <script type="text/javascript" src="{{ asset('template/admin/js/jquery-ui.js') }}" ></script>
    <!-- Datatables Js-->
    <script type="text/javascript" src="{{ asset('template/admin/js/datatables.min.js') }}"></script>

    <script>
        $('#table').DataTable({
            "language" : {
                "url" : "{{ asset('lang/' . config('app.locale') . '.json') }}"
            }
        });
    </script>

    <script type="text/javascript">
        $(function () {
            $("#table").DataTable();

            $("#table_contents").sortable({
                items: "tr",
                cursor: 'move',
                opacity: 0.6,
                update: function () {
                    sendOrderToServer();
                }
            });

            function sendOrderToServer() {

                var positions = [];
                $('tr.row1').each(function (index) {
                    positions.push({
                        id: $(this).attr('data-id'),
                        position: index + 1
                    });
                });

                $.ajax({
                    type: "POST",
                    dataType: "json",
                    url: "{{ url('admin/car/position/update') }}",
                    data: {
                        positions: positions,
                        _token: '{{csrf_token()}}'
                    }
                });
            }
        });
    </script>
    <script type='text/javascript'>
        $(document).on("submit", "form", function (e) {
            e.preventDefault();
            Swal.fire({
                title: "{{__('Are you sure?') }}",
                html: "{{__('Cette voiture ne sera plus affichée dans vos sélections !') }}",
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: "{{ __('Yes') }}",
                cancelButtonText: "{{ __('Cancel') }}",
                reverseButtons: true
            }).then((result) => {
                if (result.value) {
                    e.currentTarget.submit();
                }
            });
        });
    </script>

    <script>
        $(document).ready(function () {
            $('#trash').click(function () {
                $('#trashed_cars').toggle(500);
            });
        });
    </script>
@endsection