routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', 'CarController@index')->name('home.page');

Route::name('car.')->group(function () {
    Route::get('car/detail/{id}', 'CarController@detail')->name('detail');
});


Route::name('admin.')->prefix('admin')->namespace('Admin')->group( function (){

    Auth::routes(['verify' => true]);

    Route::get('/home', 'HomeController@index')->name('home');

    Route::resource('cars', 'CarController');
    Route::post('/car/position/update', 'CarController@update_position');
    Route::get('car/restore/{id}', 'CarController@restore')->name('car.restore');
    Route::get('cars/restore_all', 'CarController@restore_all')->name('cars.restore_all');
    Route::delete('car/delete_image', 'CarController@delete_image')->name('car.delete.image');
});


Route::group(['prefix' => 'admin'], function () {
    Route::resource('sellers', 'Admin\SellerController', ["as" => 'admin']);
});

resources/views/admin/layouts/app.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <title>228 - Car -- Admin</title>
    <meta name="description" content="CoreUI Template - InfyOm Laravel Generator">
    <meta name="keyword" content="CoreUI,Bootstrap,Admin,Template,InfyOm,Open,Source,jQuery,CSS,HTML,RWD,Dashboard">
    <!-- Bootstrap-->
    <link rel="stylesheet" href="{{ asset('template/admin/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('template/admin/css/bootstrap-datetimepicker.css') }}">

    <!-- Theme style -->
    <link rel="stylesheet" href="{{ asset('template/admin/css/coreui.min.css') }}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="{{ asset('template/admin/css/coreui-icons-free.css') }}">
    <link rel="stylesheet" href="{{ asset('template/admin/css/font-awesome.min.css') }}">
    <link rel="stylesheet" href="{{ asset('template/admin/css/simple-line-icons.css') }}">
    <link rel="stylesheet" href="{{ asset('template/admin/css/flag-icon.min.css') }}">

    <!-- Favicon icon -->
    <link rel="shortcut icon" href="{{ asset('template/home_page/img/favicon.ico') }}" type="image/x-icon">

     <!-- PRO version // if you have PRO version licence than remove comment and use it. -->
    {{--<link rel="stylesheet" href="https://unpkg.com/@coreui/icons@1.0.0/css/brand.min.css">--}}
    {{--<link rel="stylesheet" href="https://unpkg.com/@coreui/icons@1.0.0/css/flag.min.css">--}}
     <!-- PRO version -->
    <link href="{{ asset('template/admin/css/font-awesome.min.css') }}" rel="stylesheet">
    <link href="{{ asset('template/admin/css/simple-line-icons.css') }}" rel="stylesheet">
    <link href="{{ asset('template/admin/css/flag-icon.min.css') }}" rel="stylesheet">
    <style>
        input, select, textarea {border: 2px solid #ccc !important;}
        /*input {height: 40px !important;}*/
    </style>
    @yield('styles')
</head>
<body class="app header-fixed sidebar-fixed aside-menu-fixed sidebar-lg-show">
<header class="app-header navbar">
    <button class="navbar-toggler sidebar-toggler d-lg-none mr-auto" type="button" data-toggle="sidebar-show">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="#">
        <img class="navbar-brand-full" src="{{ asset('template/home_page/img/logos/black-logo.png') }}" width="80" height="50"
             alt="228Cars Logo">
        <img class="navbar-brand-minimized" src="{{ asset('template/home_page/img/logos/black-logo.png') }}" width="80" height="50"
             alt="228Cars Logo">
    </a>
    <button class="navbar-toggler sidebar-toggler d-md-down-none" type="button" data-toggle="sidebar-lg-show">
        <span class="navbar-toggler-icon"></span>
    </button>

    <ul class="nav navbar-nav ml-auto">
        <li class="nav-item d-md-down-none">
            <a class="nav-link" href="#">
                <i class="icon-bell"></i>
                <span class="badge badge-pill badge-danger">5</span>
            </a>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link" style="margin-right: 10px" data-toggle="dropdown" href="#" role="button"
               aria-haspopup="true" aria-expanded="false">
                <strong>{{ Auth::user()->full_name }}</strong>
            </a>
            <div class="dropdown-menu dropdown-menu-right">
                <div class="dropdown-header text-center">
                    <strong>Account</strong>
                </div>
                <a class="dropdown-item" href="#">
                    <i class="fa fa-envelope-o"></i> Messages
                    <span class="badge badge-success">42</span>
                </a>
                <div class="dropdown-header text-center">
                    <strong>Settings</strong>
                </div>
                <a class="dropdown-item" href="#">
                    <i class="fa fa-user"></i> Profile</a>
                <a class="dropdown-item" href="#">
                    <i class="fa fa-wrench"></i> Settings</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">
                    <i class="fa fa-shield"></i> Lock Account</a>
                <a href="{{ url('/admin/logout') }}" class="dropdown-item btn btn-default btn-flat"
                   onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                    <i class="fa fa-lock"></i>Logout
                </a>
                <form id="logout-form" action="{{ url('/admin/logout') }}" method="POST" style="display: none;">
                    @csrf
                </form>
            </div>
        </li>
    </ul>
</header>

<div class="app-body">
    @include('admin.layouts.sidebar')
    <main class="main">
        @yield('content')
    </main>
</div>
<footer class="app-footer">
    <div>
        <a href="https://infyom.com">InfyOm </a>
        <span>&copy; 2019 InfyOmLabs.</span>
    </div>
    <div class="ml-auto">
        <span>Powered by</span>
        <a href="https://coreui.io">CoreUI</a>
    </div>
</footer>
</body>
<!-- jQuery 3.1.1 -->
<script src="{{ asset('template/admin/js/jquery-3.3.1.min.js') }}"></script>
<script src="{{ asset('template/admin/js/popper.min.js') }}"></script>
<script src="{{ asset('template/admin/js/bootstrap.min.js') }}"></script>
<script src="{{ asset('template/admin/js/moment.min.js') }}"></script>
<script src="{{ asset('template/admin/js/bootstrap-datetimepicker.min.js') }}"></script>
<script src="{{ asset('template/admin/js/coreui.min.js') }}"></script>
<script src="{{ asset('template/admin/js/sweetalert2@9.js') }}"></script>
@yield('scripts')

</html>

resources/views/admin/layouts/datatables_css.blade.php
<!-- DataTable Bootstrap -->
<link href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.3.1/css/buttons.bootstrap.min.css">

resources/views/admin/layouts/datatables_js.blade.php
<!-- Datatables -->
<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.3.1/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.3.1/js/buttons.bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.3.1/js/buttons.colVis.min.js"></script>
<script src="{{ asset('vendor/datatables/buttons.server-side.js') }}"></script>

resources/views/admin/layouts/menu.blade.php
<li class="nav-item {{ Request::is('admin/cars*') ? 'active' : '' }}">
    <a class="nav-link" href="{{ route('admin.cars.index') }}">
        <i class="fa fa-car"></i>
        <span>Cars</span>
    </a>
</li>
<li class="nav-item {{ Request::is('admin/sellers*') ? 'active' : '' }}">
    <a class="nav-link" href="{{ route('admin.sellers.index') }}">
        <i class="fa fa-users"></i>
        <span>Sellers</span>
    </a>
</li>

resources/views/admin/layouts/sidebar.blade.php
<div class="sidebar">
    <nav class="sidebar-nav">
        <ul class="nav">
            @include('admin.layouts.menu')
        </ul>
    </nav>
    <button class="sidebar-minimizer brand-minimizer" type="button"></button>
</div>